language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
matrix:
  allow_failures:
    - python: "2.7"
    - python: "3.4"
  fast_finish: true

# Route build to container-based infrastructure
sudo: false
# Cache the dependencies installed by pip
cache: pip

# Install defaults to "pip install -r requirements.txt"

# Commands that prepare things for the test
before_script:
  - export PYTHONPATH=$PYTHONPATH:`pwd -P`
  - cd test

# Command to run tests
script:
  - coverage run --source=apel,bin -m unittest2 discover

after_success:
  - coveralls
