language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
matrix:
  allow_failures:
    - python: "2.7"
    - python: "3.4"
  fast_finish: true

sudo: false
cache: pip

# command to run tests, e.g. python setup.py test
script:
  - export PYTHONPATH=$PYTHONPATH:`pwd -P`
  - cd test
  - coverage run --source=apel,bin -m unittest2 discover

after_success:
  - coveralls
